CREATE TABLE tbl_credit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   credit_code UUID NOT NULL,
   credit_value DECIMAL NOT NULL,
   day_first_of_installment date NOT NULL,
   number_of_installments INT NOT NULL,
   status INT,
   customer_id BIGINT,
   CONSTRAINT pk_tbl_credit PRIMARY KEY (id)
);

ALTER TABLE tbl_credit ADD CONSTRAINT uc_tbl_credit_creditcode UNIQUE (credit_code);

ALTER TABLE tbl_credit ADD CONSTRAINT FK_TBL_CREDIT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES tbl_customer (id);