version: '3.7'
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres
    container_name: dev-postgresql
    environment:
      POSTGRES_PASSWORD: 'asdfasdf'
    ports:
      - 5433:5432
    volumes:
      - springPostgresSQL:/var/lib/postgresql/data
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me1@example.com
      PGADMIN_DEFAULT_PASSWORD: 'asdfasdf'
    ports:
      - 5050:80
    volumes:
      - springPgAdmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge

volumes:
  springPostgresSQL:
  springPgAdmin:
