spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true

#      ddl-auto: 'create-drop'


